version: "3"
volumes:
  postgresql_data:
    driver: local
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    image: my_app
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    user: ruby
    command: >
      /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/src
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      DATABASE_HOST: db
      WEBPACKER_DEV_SERVER_HOST: webpacker
      FIREBASE_PROJECT_ID: "$FIREBASE_PROJECT_ID"
    depends_on:
      - db
      - webpacker
  webpacker:
    image: my_app
    user: ruby
    command: >
      bin/webpack-dev-server
    environment:
      FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
      FIREBASE_API_KEY: "${FIREBASE_API_KEY}"
      FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}"
    volumes:
      - .:/src
    ports:
      - 3035:3035
  solargraph:
    image: my_app
    user: ruby
    command: >
      bundle exec solargraph socket --host=0.0.0.0 --port=7658
    volumes:
      - .:/src
    ports:
      - 7658:7658
    depends_on:
      - app
